version: '3.8'
services:
  postgres:
    container_name: support-eng-notifier-postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: "support-eng-notifier"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./local-setup/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d support-eng-notifier" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
