#Fri Feb 09 11:19:25 UTC 2024
micronaut:
  application:
    name: "support-eng-notifier"
  http:
    services:
      backoffice:
        urls: ${BACKOFFICE_URL}
        auth-token: ${BACKOFFICE_AUTH_TOKEN}
        connection-pool-idle-timeout: 5m
        connect-timeout: 500ms
        log-level: DEBUG
        pool:
          enabled: true
          max-connections: 10
        read-timeout: 3s
      order-ledger:
        urls: ${ORDER_LEDGER_URL}
        connection-pool-idle-timeout: 5m
        connect-timeout: 500ms
        log-level: DEBUG
        pool:
          enabled: true
          max-connections: 10
        read-timeout: 3s
  security:
    enabled: true # by default
    oauth2:
      clients:
        order-ledger-auth0:
          client-id: ${OAUTH2_CLIENT_ID}
          client-secret: ${OAUTH2_CLIENT_SECRET}
          grant-type: client_credentials
          token:
            url: ${AUTH0_ISSUER}/oauth/token
            auth-method: client_secret_post
          client-credentials:
            service-id-regex: order-ledger
            additional-request-params:
              audience: ${AUTH0_ORDER_LEDGER_AUDIENCE}
endpoints:
  health:
    enabled: true
datasources:
  migration:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/support-eng-notifier
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    ssl: ${POSTGRES_SSL:false}
flyway:
  datasources:
    migration:
      enabled: true
      locations: classpath:migrations
r2dbc:
  datasources:
    default:
      options:
        driver: pool
        protocol: postgresql
        initialSize: 3
        maxSize: 10
        maxIdleTime: PT5m
        backgroundEvictionInterval: PT5m
        minIdle: 0
        maxAcquireTime: PT10S
        maxCreateConnectionTime: PT10S
        maxValidationTime: PT10S
        maxLifeTime: PT30m
      url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/support-eng-notifier
      username: ${POSTGRES_USER:postgres}
      password: ${POSTGRES_PASSWORD:password}
      ssl: ${POSTGRES_SSL:false}
